php:
    preset: recommended
    finder:
        exclude:
            - modules
            - node_modules
            - storage
            - vendor
        name: "*.php"
        not-name: "*.blade.php"
