language: php

php:
    - 7.2
    - 7.3

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml

after_script:
    - php vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml
    - bash <(curl -s https://codecov.io/bash) -t 826813e7-0cd1-4dfb-9f0f-b5aabc056d0f
