name: PHP Composer

on: [push]

jobs:
    test:
        strategy:
            matrix:
                platform: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            -   uses: actions/checkout@v1
            -   uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: ./coverage.xml
                    flags: unittests
                    name: codecov-umbrella
                    yml: ./codecov.yml
            -   uses: actions/checkout@v1
            -   name: PHPCodeSniffer
                uses: rtCamp/action-phpcs-inspection@v1.0.0
            -   name: PHP Insights Action
                uses: stefanzweifel/phpinsights-action@v1.0.0
            -   name: EditorConfig-Action
                uses: zbeekman/EditorConfig-Action@v1.1.1
            -   name: PHPUnit (php-actions)
                uses: php-actions/phpunit@v1.0.0
            -   name: Running composer scripts
                run: composer run-script test
