name: PHP Composer

on: [push]

jobs:
  build:

  runs-on: [ubuntu-latest, macos-latest, windows-latest]

  steps:
      -   uses: actions/checkout@master
      -   uses: codecov/codecov-action@v1
          with:
              token: ${{ secrets.826813e7-0cd1-4dfb-9f0f-b5aabc056d0f }}
              file: ./coverage.xml
              flags: unittests
              name: codecov-umbrella
              yml: ./codecov.yml
              fail_ci_if_error: true
      -   name: PHPCodeSniffer
          uses: rtCamp/action-phpcs-inspection@v1.0.0
      -   name: PHP Insights Action
          uses: stefanzweifel/phpinsights-action@v1.0.0
      -   name: EditorConfig-Action
          uses: zbeekman/EditorConfig-Action@v1.1.1
      -   name: PHPUnit (php-actions)
          uses: php-actions/phpunit@v1.0.0
      -   name: Running composer scripts
          run: composer run-script test
